vidlinks = new Map([
    ["11 Eyes OP 1", "https://www.youtube.com/watch?v=VYTkJDhKcc4"],
    ["7 Deadly Sins OP 1", "https://www.youtube.com/watch?v=kuj4d1TWesQ"],
    ["7 Deadly Sins S2 OP 2", "https://www.youtube.com/watch?v=4QkEZl34wCo"],
    ["A Certain Magical Index II OP 1", "https://www.youtube.com/watch?v=YKvnc7z0roM"],
    ["A Certain Magical Index III OP 2", "https://www.youtube.com/watch?v=tJzF1tu7-dw"],
    ["Absolute duo OP 1", "https://www.youtube.com/watch?v=1CBctbw3c0s"],
    ["Accel World OP 2", "https://www.youtube.com/watch?v=IGRAfhYEYKM"],
    ["AICO Incarnation OP 1", "https://www.youtube.com/watch?v=oq9fFLVSroA"],
    ["Akame Ga Kill OP 1", "https://www.youtube.com/watch?v=mJz8F-hHpnM"],
    ["Akame Ga Kill OP 2", "https://www.youtube.com/watch?v=v7A_wIGklDg"],
    ["Alderamin on the sky OP 1", "https://www.youtube.com/watch?v=kOG6Fd_xyxg"],
    ["Aldnoah.Zero OP 1", "https://www.youtube.com/watch?v=mi2YE1-yeYs"],
    ["Amnesia OP 1", "https://www.youtube.com/watch?v=Zx7O4hhsI1M"],
    ["Ancient Magus Bride OP 1", "https://www.youtube.com/watch?v=KuZbmLLv1vM"],
    ["Angel Beats OP 1", "https://www.youtube.com/watch?v=-hA4na_3jT0"],
    ["Angolmois OP 1", "https://www.youtube.com/watch?v=gdN4XDLa64o"],
    ["Anohana OP 1", "https://www.youtube.com/watch?v=o1JrFtycErY"],
    ["Another OP", "https://www.youtube.com/watch?v=kupW7eDG48s"],
    ["Arlan Senki OP 3", "https://youtu.be/f0aw5pqlOWY?t=6"],
    ["Assassination Classroom OP 1", "https://www.youtube.com/watch?v=KS9UfmCFn_Y"],
    ["Assassination Classroom S2 OP 2", "https://www.youtube.com/watch?v=c_J7ybxenOQ"],
    ["Asterisk War OP 1", "https://www.youtube.com/watch?v=vZBUJxsU5U4"],
    ["Attack On Titan OP 1", "https://www.youtube.com/watch?v=XMXgHfHxKVM"],
    ["Attack On Titan S2 OP 1", "https://www.youtube.com/watch?v=LKP-vZvjbh8"],
    ["Attack On Titan S3 OP 1", "https://www.youtube.com/watch?v=swwUoExDIng"],
    ["Baccano! OP 1", "https://www.youtube.com/watch?v=OOZ1hsb8smQ"],
    ["Baka And Test OP 1", "https://www.youtube.com/watch?v=CXW9KqRVa7E"],
    ["Bakemonogatari OP 1", "https://www.youtube.com/watch?v=z-caezFDfTs"],
    ["Barakamon OP ", "https://www.youtube.com/watch?v=NM8y4NLBWkw"],
    ["Berserk 2016 OP 1", "https://www.youtube.com/watch?v=q2SWV5xxtcQ"],
    ["Black Butler Book of Circus OP 1", "https://youtu.be/M22jx3PNxr0?t=5"],
    ["Black Butler OP 1", "https://youtu.be/1Y9nulcg3Yw?t=1"],
    ["Black Clover OP 3", "https://www.youtube.com/watch?v=dsK8SsfqdHE"],
    ["Black Clover OP 4", "https://www.youtube.com/watch?v=cK9Z9Zcuso0"],
    ["Black Lagoon OP 1", "https://youtu.be/dWfxcRj39tg?t=3"],
    ["Bleach OP 13", "https://www.youtube.com/watch?v=XXjgwpayNoM"],
    ["Bleach OP 14", "https://www.youtube.com/watch?v=ifrTLAd6UQY"],
    ["Blend S OP 1", "https://www.youtube.com/watch?v=dv7MYtlnNus"],
    ["Blood+ OP 3", "https://www.youtube.com/watch?v=KSI_lwmtcoo"],
    ["Blue Exorcist OP 2", "https://www.youtube.com/watch?v=5ZPELMm-W68"],
    ["Blue Exorcist S2 OP 1", "https://www.youtube.com/watch?v=2hw9setFP4k"],
    ["Boogiepop Phantom (2018) OP 1", "https://www.youtube.com/watch?v=oBbWSxqJSOI"],
    ["BTOOOM OP 1", "https://www.youtube.com/watch?v=JWIlePu_XV4"],
    ["Bungou Stray Dogs OP 1", "https://www.youtube.com/watch?v=tvHqaimwcKE"],
    ["Bungou Stray Dogs OP 2", "https://www.youtube.com/watch?v=v9OhNoPAZJY"],
    ["Bunny Girl Senpai OP 1", "https://www.youtube.com/watch?v=z1PWA11Ec3E"],
    ["Caligula OP 1", "https://www.youtube.com/watch?v=a5hp33QFewk"],
    ["Cardcaptor Sakura: Clear Card OP 1", "https://www.youtube.com/watch?v=sbwT8yJjtUQ"],
    ["Carnival Phantasm OP 1", "https://www.youtube.com/watch?v=62c7_zKoSV8"],
    ["Carole and Tuesday", "https://www.youtube.com/watch?v=jsNm1LQUrXM"],
    ["Cells at work OP 1", "https://www.youtube.com/watch?v=QYfdanAahVI"],
    ["Chivalry of a Failed Knight OP 1", "https://www.youtube.com/watch?v=y1H_VTSgJbU"],
    ["Clannad After Story OP 1", "https://www.youtube.com/watch?v=hVMJxT3O9qA"],
    ["Classroom of the Elite", "https://www.youtube.com/watch?v=kMBaVZqUXYY"],
    ["Code Geass OP 1", "https://www.youtube.com/watch?v=G8CFuZ9MseQ"],
    ["Code Geass R2 OP 1", "https://www.youtube.com/watch?v=AgWI4EQ78ik"],
    ["Conception OP 1", "https://www.youtube.com/watch?v=KbbYPgf9dEI"],
    ["Cop Craft OP 1", "https://www.youtube.com/watch?v=9MNLpx5jtV4"],
    ["Cowboy Bebop OP 1", "https://www.youtube.com/watch?v=NRI_8PUXx2A"],
    ["D. Gray Man OP 1", "https://www.youtube.com/watch?v=iSGCKUU044A"],
    ["D. Gray Man OP 2", "https://www.youtube.com/watch?v=NcGqD2Q4Y_I"],
    ["Danmachi OP 1", "https://www.youtube.com/watch?v=0H_RCGEcjhs&t"],
    ["Darker Than Black OP 1", "https://www.youtube.com/watch?v=MYPmYSHWgMQ"],
    ["Darling in the Franxx OP 1", "https://www.youtube.com/watch?v=A4kLcDWBYcQ"],
    ["Day Break Illusion OP 1", "https://youtu.be/juRsXaqOTd0?t=1"],
    ["Deadman Wonderland OP 1", "https://www.youtube.com/watch?v=xc7f5tAD5U8"],
    ["Death Note OP 1", "https://www.youtube.com/watch?v=8QE9cmfxx4s"],
    ["Death Parade OP 1", "https://www.youtube.com/watch?v=UjjTMNDZi-A"],
    ["Demon Slayer OP 1", "https://www.youtube.com/watch?v=pmanD_s7G3U"],
    ["Diabolik Lovers OP 1", "https://www.youtube.com/watch?v=w6hyZbaDKA8"],
    ["Dimension W OP 1", "https://www.youtube.com/watch?v=9Cqzz88jrxY"],
    ["Dirty Pair OP 1", "https://www.youtube.com/watch?v=pTMe1vhUxh0"],
    ["Divine Gate", "https://www.youtube.com/watch?v=WLWD-DcP0ko"],
    ["Domestic Girlfriend OP 1", "https://www.youtube.com/watch?v=ywhzUjQjjGI"],
    ["Dororo OP 1", "https://www.youtube.com/watch?v=5DCGQ57ykME"],
    ["Dr. Stone OP 1", "https://www.youtube.com/watch?v=tF4faMbs5oQ"],
    ["Dragon Ball Super OP 2", "https://www.youtube.com/watch?v=Li76Oh-HdIw"],
    ["Drifters OP 1", "https://www.youtube.com/watch?v=cXabZ_-QPb0"],
    ["Durarara OP 1", "https://www.youtube.com/watch?v=WNt8zC9zjEk"],
    ["Ef: A Tale Of Melodies OP", "https://www.youtube.com/watch?v=Egmf2bl6HoI"],
    ["Ef: A Tale Of Memories OP", "https://www.youtube.com/watch?v=05fbwE5RMSs"],
    ["Elfen Lied OP 1", "https://www.youtube.com/watch?v=pKG3m4uTSyw"],
    ["Erased OP 1", "https://www.youtube.com/watch?v=Y9G20wV0KHE"],
    ["Eromanga Sensei OP 1", "https://www.youtube.com/watch?v=DeGw8-KwxM4"],
    ["Fairy Tail OP 16", "https://youtu.be/EXIxL6w5Yuk"],
    ["Fairy Tail OP 22", "https://www.youtube.com/watch?v=e-7uuV7B7mo"],
    ["Fate/Apocrypha OP 1", "https://www.youtube.com/watch?v=3nLH06ftkL0"],
    ["Fate/Stay Night UBW OP 2", "https://www.youtube.com/watch?v=-yvMqox7c6A"],
    ["Fate/Zero OP 2", "https://www.youtube.com/watch?v=r1JJUk7Cl7A"],
    ["Fire Force OP 1", "https://www.youtube.com/watch?v=NjchjvO8Zks"],
    ["Food Wars OP 1", "https://www.youtube.com/watch?v=vV3l_1j8pPE"],
    ["Free OP 1", "https://www.youtube.com/watch?v=oveSIRPMJYA"],
    ["Full Metal Panic! IV OP 1", "https://www.youtube.com/watch?v=6rSPh3uuoQM"],
    ["Fullmetal Alchemist B OP 1", "https://www.youtube.com/watch?v=2uq34TeWEdQ"],
    ["Fullmetal Alchemist B OP 5", "https://www.youtube.com/watch?v=cRA5gsdCf4c"],
    ["Fullmetal Alchemist OP 4", "https://www.youtube.com/watch?v=ORe7gt-mY14"],
    ["Future Diary OP 1", "https://youtu.be/DbqykQH1ZME?t=3"],
    ["Future Diary OP 2", "https://www.youtube.com/watch?v=0_36iNzrEn0"],
    ["Gangsta OP 1", "https://youtu.be/COBpRXm_CUQ?t=6"],
    ["Gantz OP", "https://www.youtube.com/watch?v=MCp8pw2l688"],
    ["Gatchaman Crowds OP 1", "https://www.youtube.com/watch?v=UwMi7KSDf5g"],
    ["Gatchaman Crowds OP 2", "https://www.youtube.com/watch?v=KKlrPon5KbU"],
    ["Gate OP 2", "https://www.youtube.com/watch?v=fcCJhQrGcEQ"],
    ["Ghost In The Shell SAC OP 1", "https://www.youtube.com/watch?v=QxkMzn4et2U"],
    ["Gintama OP 1", "https://www.youtube.com/watch?v=REHaJZgWwxY"],
    ["Goblin Slayer OP 1", "https://www.youtube.com/watch?v=0i0z98M2y5U"],
    ["Golden Kamuy OP 2", "https://www.youtube.com/watch?v=uEL-RZ5PKgQ"],
    ["Gosick OP 1", "https://www.youtube.com/watch?v=iOrkj_MFXm8"],
    ["Granbelm OP 1", "https://www.youtube.com/watch?v=SzsBE4lNs8o"],
    ["Grimgar of Fantasy and Ash", "https://www.youtube.com/watch?v=-rIE7Qr4J0U"],
    ["Guilty Crown OP 1", "https://www.youtube.com/watch?v=xmh3mNvgJBs"],
    ["Guilty Crown OP 2", "https://www.youtube.com/watch?v=gdanLoW6FgI"],
    ["Gurren Lagann OP 1", "https://www.youtube.com/watch?v=KClW6qi020w"],
    ["Haikyuu OP 1", "https://www.youtube.com/watch?v=2---3Iysnqg"],
    ["Haiyore Nyaruko San OP 2", "https://www.youtube.com/watch?v=Yose5jKIIVY&t=1s"],
    ["Hakata Tonkatsu Ramens OP 1", "https://www.youtube.com/watch?v=JrVt1hPpkVM"],
    ["Hanebado! OP 1", "https://www.youtube.com/watch?v=EwWG_wPuT6c"],
    ["Hellsing OP 1", "https://www.youtube.com/watch?v=hMNJwUUHMxc"],
    ["Hibike! Euphonium OP 1", "https://www.youtube.com/watch?v=RZqLaAORteg"],
    ["High school dxd hero OP 1", "https://www.youtube.com/watch?v=wrNvWEEHzTk&t=11s"],
    ["Highschool of the Dead OP 1", "https://www.youtube.com/watch?v=TQwQMeb-44g"],
    ["Higurashi No Naku Koro Ni OP 1", "https://www.youtube.com/watch?v=XgWkIrFQQE0"],
    ["Hinamatsuri OP 1", "https://www.youtube.com/watch?v=tJVAkofTFbI"],
    ["Hunter X Hunter New OP 1", "https://www.youtube.com/watch?v=faqmNf_fZlE"],
    ["Hyouka OP 1", "https://www.youtube.com/watch?v=Msuu3b-L-2k"],
    ["Initial D final stage OP 1", "https://youtu.be/_FsCuvh25tY?t=4"],
    ["Inu X Boku SS OP 1", "https://youtu.be/WpJ8oP0ZWoc?t=1"],
    ["Inuyasha OP 3", "https://www.youtube.com/watch?v=p56pg3EMJLE"],
    ["Inuyasha OP 4", "https://www.youtube.com/watch?v=4v0lSXBcJIU"],
    ["Inuyashiki OP", "https://www.youtube.com/watch?v=AFnF2E6nJDw"],
    ["Jojo Part 2 OP", "https://www.youtube.com/watch?v=OpUbnLjexTc"],
    ["Jojo Part 5 OP 1", "https://www.youtube.com/watch?v=OchozLuSHM0"],
    ["Jormungand OP 1", "https://www.youtube.com/watch?v=uDhEtUl7U-A"],
    ["Juuni Taisen OP", "https://www.youtube.com/watch?v=kR50SHtj-Og"],
    ["K-ON! OP 1", "https://www.youtube.com/watch?v=m7_-RBl0lfY"],
    ["Kabeneri of the Iron Fortress OP 1", "https://www.youtube.com/watch?v=0w-9u4SxWwc"],
    ["Kaguya-Sama: Love is War OP 1", "https://www.youtube.com/watch?v=gChTHeHp3wQ"],
    ["Kakegurui OP 1", "https://www.youtube.com/watch?v=UOAC6GYYY-4"],
    ["Keijo!!! OP 1", "https://www.youtube.com/watch?v=Cq9cM0D_fZU"],
    ["Kekkai Sensen OP 1", "https://youtu.be/4J8jcI0WtzM?t=6"],
    ["Kekkai Sensen OP 2", "https://www.youtube.com/watch?v=_16vOCt-sYk"],
    ["Kill la Kill OP 1", "https://www.youtube.com/watch?v=ci3A3OmNHko"],
    ["Kill la Kill OP 2", "https://www.youtube.com/watch?v=qaLeO-2Fytg"],
    ["Kimi no Na Wa OP", "https://youtu.be/qssaTnBiHLo?t=90"],
    ["Koi To Uso OP 1", "https://www.youtube.com/watch?v=VrmzXR1sI78"],
    ["Kokkoku OP", "https://www.youtube.com/watch?v=fhBA6ynorvc"],
    ["Konosuba OP 2", "https://www.youtube.com/watch?v=4JpR-M1wE5s"],
    ["Kore Wa Zombie Desu Ka OP 1", "https://www.youtube.com/watch?v=vPvNWbVSEb0"],
    ["Kuroko no Basuke 3 OP 1", "https://www.youtube.com/watch?v=089nwtLOLmU"],
    ["Kuroko no Basuke OP 1", "https://www.youtube.com/watch?v=LIBPhMB4nZw"],
    ["Kyoukai no Kanata", "https://www.youtube.com/watch?v=NqxJ191ecPQ"],
    ["Laid-Back Camp OP 1", "https://www.youtube.com/watch?v=7-EwChG1WTA"],
    ["Land of the Lustrous OP 1", "https://www.youtube.com/watch?v=C9MuI4gfyiA"],
    ["Little Witch Academia OP 1", "https://www.youtube.com/watch?v=JRmgL564x8E"],
    ["Log Horizon OP 1", "https://www.youtube.com/watch?v=CZ73Qv-RQNg"],
    ["Lucky Star OP 1", "https://www.youtube.com/watch?v=03x0bU2w9HI"],
    ["Made In Abyss OP 1", "https://www.youtube.com/watch?v=e91G8m9uM_0"],
    ["Madoka Magica op 1", "https://www.youtube.com/watch?v=OrgpX-_bFqM"],
    ["Magi OP 1", "https://www.youtube.com/watch?v=M8JuOhB7-U0"],
    ["Magic Kaito 1412 OP 2", "https://www.youtube.com/watch?v=Q9esf5COzck"],
    ["March Comes In Like A Lion OP 4", "https://www.youtube.com/watch?v=5htUWLGqlnQ"],
    ["Megalo Box OP 1", "https://www.youtube.com/watch?v=ByMrJy5p7q8"],
    ["Mekakucity Actors OP 1", "https://www.youtube.com/watch?v=_1hNaDmBS-U"],
    ["Mob Psycho OP 1", "https://www.youtube.com/watch?v=Bw-5Lka7gPE"],
    ["Mob Psycho OP 2", "https://www.youtube.com/watch?v=epZaT8B31-g"],
    ["MSG Iron Blooded Orphans OP 1", "https://www.youtube.com/watch?v=FjXS_lbU2TU"],
    ["MSG Iron Blooded Orphans OP 2", "https://www.youtube.com/watch?v=qBchWCnMv8U"],
    ["Mononoke OP 1", "https://www.youtube.com/watch?v=OKbcBnu6FtI"],
    ["My Hero Aca S1 OP", "https://www.youtube.com/watch?v=yu0HjPzFYnY"],
    ["My Hero Aca S2 OP 1", "https://www.youtube.com/watch?v=Q7w5IMyJ3pM"],
    ["Naruto OP 4", "https://www.youtube.com/watch?v=xjBTNbEXbAA"],
    ["Naruto Shippuden OP 16", "https://www.youtube.com/watch?v=otxA7fpPMPc"],
    ["Naruto Shippuden OP 3", "https://www.youtube.com/watch?v=2upuBiEiXDk"],
    ["Neon Genesis Evangelion op", "https://www.youtube.com/watch?v=t-QSmNReDyI"],
    ["Nichijou OP 1", "https://www.youtube.com/watch?v=qUk1ZoCGqsA"],
    ["Nisekoi OP 1", "https://www.youtube.com/watch?v=ikkBnTZxGbE"],
    ["Nisemonogatari OP 3", "https://www.youtube.com/watch?v=Y8SwZJAUiW4"],
    ["No Game No Life OP 1", "https://www.youtube.com/watch?v=NQCax11Q0Bs"],
    ["Noragami Aragoto OP 1", "https://youtu.be/3oFTHxkOzjE?t=7"],
    ["Noragami OP 1", "https://www.youtube.com/watch?v=inq4vsIn6zA"],
    ["One Piece OP 22", "https://youtu.be/necK0u6i5pA"],
    ["One Piece OP 6", "https://www.youtube.com/watch?v=AL8m1Uktt4c"],
    ["One Punch Man OP 1", "https://www.youtube.com/watch?v=atxYe-nOa9w"],
    ["Ouran High School Host Club OP 1", "https://www.youtube.com/watch?v=QXSBh4gtQ7g"],
    ["Outlaw Star OP 1", "https://www.youtube.com/watch?v=3LucBfR1w6Y"],
    ["Overlord S1 OP", "https://www.youtube.com/watch?v=KOWcj7XKnfQ"],
    ["Overlord S2 OP", "https://www.youtube.com/watch?v=lfpyJUnwW0w"],
    ["Owarimonogatari OP 1", "https://www.youtube.com/watch?v=PWXNvCg3uT0"],
    ["Pandora Hearts OP 1", "https://www.youtube.com/watch?v=bmFRFjosVI0"],
    ["Parasyte OP 1", "https://www.youtube.com/watch?v=4h6Mdhu8U-k"],
    ["Perfect Insider OP", "https://www.youtube.com/watch?v=BWxX4S42uK0"],
    ["Persona 5 The Animation OP 2", "https://www.youtube.com/watch?v=_F6LD_czS8s"],
    ["Piano no Mori OP 1", "https://www.youtube.com/watch?v=M8oyfP4XKeM"],
    ["Ping Pong The Animation OP 1", "https://www.youtube.com/watch?v=2v6iOVhw6mQ"],
    ["Pokemon OP 1", "https://www.youtube.com/watch?v=6xKWiCMKKJg"],
    ["Pokemon XYZ OP 1", "https://www.youtube.com/watch?v=CQuObfTx6Cg"],
    ["Pop Team Epic OP 1", "https://www.youtube.com/watch?v=TmrosfxGifQ"],
    ["Promised Neverland OP 1", "https://www.youtube.com/watch?v=1JoFsTDfd-8"],
    ["Psycho pass OP 1", "https://www.youtube.com/watch?v=WWBDuVCuiUQ"],
    ["Psycho pass OP 2", "https://www.youtube.com/watch?v=irqFRZqptWg"],
    ["Quan Zhi Gao Shou", "https://www.youtube.com/watch?v=RgmPcvK7nBA"],
    ["Rage of Bahamut Virgin soul OP 2", "https://www.youtube.com/watch?v=YOLE_WCYKZQ"],
    ["Re:Creators OP 1", "https://www.youtube.com/watch?v=MEEVGqvvXbI"],
    ["Re:Hamatora OP 1", "https://www.youtube.com/watch?v=f74_M9-o9do"],
    ["Re:Zero OP 1", "https://www.youtube.com/watch?v=0Vwwr3VGsYg"],
    ["Re:Zero OP 2", "https://www.youtube.com/watch?v=YjzzLB6dk6o"],
    ["Riddle Story Of Devil OP 1", "https://www.youtube.com/watch?v=TyDGMpg-3BM"],
    ["Rising of the Shield Hero OP 1", "https://www.youtube.com/watch?v=jZvFEtR8RH0"],
    ["Robotics;Notes", "https://www.youtube.com/watch?v=_bEBvS-zrh4"],
    ["Saga of Tanya The Evil OP 1", "https://www.youtube.com/watch?v=fggISqEyuew"],
    ["Sailor Moon OP 1", "https://www.youtube.com/watch?v=5txHGxJRwtQ"],
    ["Samurai Champloo", "https://www.youtube.com/watch?v=Eq6EYcpWB_c"],
    ["SAO Alicization OP 1", "https://www.youtube.com/watch?v=i_Y-GwM6o5M"],
    ["SAO II OP 1", "https://www.youtube.com/watch?v=S5jdgnuMTWk"],
    ["SAO OP 1", "https://www.youtube.com/watch?v=xiz0utrFdHU"],
    ["Selector Spread Wixoss", "https://www.youtube.com/watch?v=T3TFuFcFfec"],
    ["Seraph of the End OP 1", "https://youtu.be/aNgT6MxOURQ?t=7"],
    ["Shakugan no Shana OP 3", "https://www.youtube.com/watch?v=-jdkQYTqh9U"],
    ["Shiki OP 1", "https://www.youtube.com/watch?v=Iw5u3QVdHjA"],
    ["Slime OP 1", "https://www.youtube.com/watch?v=u67olZLcDPc"],
    ["Soul Eater OP 1", "https://www.youtube.com/watch?v=zzJ8U8OtEsE"],
    ["Soul Eater OP 2", "https://www.youtube.com/watch?v=-eYK3YP524A"],
    ["Space Brothers OP 7", "https://www.youtube.com/watch?v=uG608A_RYl8"],
    ["Spice and Wolf OP 1", "https://www.youtube.com/watch?v=MN_WgwEmRaw"],
    ["Steins;Gate 0 OP 1", "https://www.youtube.com/watch?v=1xJbdY9B3A8"],
    ["Steins:Gate OP 1", "https://www.youtube.com/watch?v=dd7BILZcYAY"],
    ["Taboo Tattoo OP 1", "https://www.youtube.com/watch?v=2y5bvEdkAj8"],
    ["Tales of Zestiria The X OP 1", "https://www.youtube.com/watch?v=9vjsu3Lb9Co"],
    ["Tamako Love Story op", "https://www.youtube.com/watch?v=kABrOnLH5LA"],
    ["The Devil Is A Part-Timer OP 1", "https://www.youtube.com/watch?v=oe9gQt-x_BE"],
    ["The Irregular at Magic High School OP 1", "https://www.youtube.com/watch?v=68lDew_mVz4"],
    ["The Irregular at Magic High School OP 2 ", "https://www.youtube.com/watch?v=b6pNl7qejNw"],
    ["The World God Only Knows OP 1", "https://www.youtube.com/watch?v=8muiDhiRb_M"],
    ["To Be Heroine OP 1", "https://www.youtube.com/watch?v=N9GA4TxlEy0"],
    ["Tokyo Ghoul RE OP 1", "https://drive.google.com/file/d/1UiFD6BzCrdZSFftrvl3jtUHlHCz3sCuy/view?usp=sharing"],
    ["Tokyo Ghoul RE OP 2", "https://www.youtube.com/watch?v=ZCCG3oQKu90"],
    ["Tokyo Ghoul S1 OP 1", "https://youtu.be/7aMOurgDB-o?t=6"],
    ["Toradora OP 1", "https://www.youtube.com/watch?v=Y3Xmzu0OtS8"],
    ["Trigun", "https://www.youtube.com/watch?v=4OxFSy8G5wk&t=11s"],
    ["Trinity Seven OP 1", "https://www.youtube.com/watch?v=7luicYAiR2g"],
    ["Tsurune OP 1", "https://www.youtube.com/watch?v=pyjklwDUJso"],
    ["Twin Star Exorcists OP 1", "https://www.youtube.com/watch?v=Zn7VLgaafSM"],
    ["Twin Star Exorcists OP 2", "https://www.youtube.com/watch?v=blD1-ekFg9U"],
    ["Umineko No Naku Koro Ni OP 3", "https://www.youtube.com/watch?v=rzbIDkR0ckU"],
    ["Vampire Knight Guilty OP", "https://www.youtube.com/watch?v=ErybW_0V5nk"],
    ["Vinland Saga", "https://www.youtube.com/watch?v=xEVcTStgA4A"],
    ["Violet Evergarden OP 1", "https://www.youtube.com/watch?v=mtuwpsc8KKI"],
    ["Watamote OP 1", "https://www.youtube.com/watch?v=gZYq7rat9d4"],
    ["Welcome to the NHK OP 1", "https://www.youtube.com/watch?v=hHs5AjAvFoA"],
    ["Wotakoi OP 1", "https://www.youtube.com/watch?v=qHNUEyCb564"],
    ["Yamada-kun to 7-Nin Majo OP 1", "https://www.youtube.com/watch?v=QHFif7LRylw"],
    ["Your Lie in April OP 1", "https://www.youtube.com/watch?v=2Ex3bu6CxPU"],
    ["Yugioh 5Ds English OP 1", "https://www.youtube.com/watch?v=BV0STuwQ6QM"],
    ["Yugioh English OP 1", "https://youtu.be/Cb3ggoyqXmU?t=42"],
    ["Yugioh GX English OP 1", "https://www.youtube.com/watch?v=CN_DjYDHEVU"],
    ["Yuri On Ice OP 1", "https://www.youtube.com/watch?v=ORDXWrL5EuQ"],
    ["Zombieland Saga OP 1", "https://www.youtube.com/watch?v=W22SxsxXTWc"]
]);

teams1 = [              // Matchups
    ["Gurren Lagann OP 1", "Baka And Test OP 1"],
    ["Promised Neverland OP 1", "Hunter X Hunter New OP 1"],
    ["My Hero Aca S2 OP 1", "Day Break Illusion OP 1"],
    ["Asterisk War OP 1", "Grimgar of Fantasy and Ash"],
    ["Ouran High School Host Club OP 1", "Future Diary OP 2"],
    ["Jojo Part 2 OP", "Pandora Hearts OP 1"],
    ["Kill la Kill OP 1", "AICO Incarnation OP 1"],
    ["Steins:Gate OP 1", "Vampire Knight Guilty OP"],
    ["Bleach OP 14", "Space Brothers OP 7"],
    ["Classroom of the Elite", "Fullmetal Alchemist OP 4"],
    ["Black Clover OP 3", "Megalo Box OP 1"],
    ["Fairy Tail OP 22", "Food Wars OP 1"],
    ["Dororo OP 1", "Hellsing OP 1"],
    ["Neon Genesis Evangelion op", "Nisemonogatari OP 3"],
    ["Demon Slayer OP 1", "Anohana OP 1"],
    ["Pokemon XYZ OP 1", "Trinity Seven OP 1"],
    ["Death Parade OP 1", "Watamote OP 1"],
    ["Kill la Kill OP 2", "Lucky Star OP 1"],
    ["Steins;Gate 0 OP 1", "Akame Ga Kill OP 1"],
    ["Kakegurui OP 1", "Boogiepop Phantom (2018) OP 1"],
    ["Domestic Girlfriend OP 1", "Ancient Magus Bride OP 1"],
    ["Seraph of the End OP 1", "Highschool of the Dead OP 1"],
    ["Pokemon OP 1", "Hinamatsuri OP 1"],
    ["Nichijou OP 1", "Angel Beats OP 1"],
    ["Persona 5 The Animation OP 2", "Aldnoah.Zero OP 1"],
    ["MSG Iron Blooded Orphans OP 1", "7 Deadly Sins OP 1"],
    ["Mekakucity Actors OP 1", "Inuyasha OP 4"],
    ["Yugioh English OP 1", "Twin Star Exorcists OP 1"],
    ["Twin Star Exorcists OP 2", "Angolmois OP 1"],
    ["Yugioh GX English OP 1", "Eromanga Sensei OP 1"],
    ["Zombieland Saga OP 1", "Tales of Zestiria The X OP 1"],
    ["Kimi no Na Wa OP", "Rage of Bahamut Virgin soul OP 2"]
]

teams2 = [              // Matchups
    ["Dragon Ball Super OP 2", "One Piece OP 6"],
    ["Caligula OP 1", "Full Metal Panic! IV OP 1"],
    ["Naruto Shippuden OP 3", "Higurashi No Naku Koro Ni OP 1"],
    ["Shakugan no Shana OP 3", "Black Butler Book of Circus OP 1"],
    ["Goblin Slayer OP 1", "To Be Heroine OP 1"],
    ["Kuroko no Basuke 3 OP 1", "Code Geass R2 OP 1"],
    ["Kekkai Sensen OP 1", "Elfen Lied OP 1"],
    ["Attack On Titan S2 OP 1", "Fairy Tail OP 16"],
    ["Your Lie in April OP 1", "Log Horizon OP 1"],
    ["Dimension W OP 1", "Tokyo Ghoul RE OP 1"],
    ["Noragami OP 1", "Bakemonogatari OP 1"],
    ["Fullmetal Alchemist B OP 1", "Welcome to the NHK OP 1"],
    ["Granbelm OP 1", "Fullmetal Alchemist B OP 5"],
    ["Cop Craft OP 1", "Owarimonogatari OP 1"],
    ["Hyouka OP 1", "High school dxd hero OP 1"],
    ["Tokyo Ghoul RE OP 2", "Drifters OP 1"],
    ["11 Eyes OP 1", "Erased OP 1"],
    ["Land of the Lustrous OP 1", "A Certain Magical Index II OP 1"],
    ["Blue Exorcist S2 OP 1", "One Piece OP 21"],
    ["Code Geass OP 1", "Gantz OP"],
    ["Re:Creators OP 1", "Piano no Mori OP 1"],
    ["Violet Evergarden OP 1", "Blue Exorcist OP 2"],
    ["The Irregular at Magic High School OP 1", "Black Lagoon OP 1"],
    ["Divine Gate", "The Irregular at Magic High School OP 2 "],
    ["Re:Zero OP 2", "Clannad After Story OP 1"],
    ["Death Note OP 1", "Blend S OP 1"],
    ["SAO Alicization OP 1", "Hakata Tonkatsu Ramens OP 1"],
    ["Hanebado! OP 1", "The World God Only Knows OP 1"],
    ["Overlord S1 OP", "Dirty Pair OP 1"],
    ["Mob Psycho OP 1", "Toradora OP 1"],
    ["Pop Team Epic OP 1", "Outlaw Star OP 1"],
    ["Magi OP 1", "D. Gray Man OP 2"]
]

teams3 = [              // Matchups
    ["Free OP 1", "Hibike! Euphonium OP 1"],
    ["SAO II OP 1", "Blood+ OP 3"],
    ["Attack On Titan S3 OP 1", "Noragami Aragoto OP 1"],
    ["Samurai Champloo", "Shiki OP 1"],
    ["No Game No Life OP 1", "Bungou Stray Dogs OP 2"],
    ["Mob Psycho OP 2", "Diabolik Lovers OP 1"],
    ["Soul Eater OP 2", "Wotakoi OP 1"],
    ["Selector Spread Wixoss", "Spice and Wolf OP 1"],
    ["Black Butler OP 1", "Haiyore Nyaruko San OP 2"],
    ["Guilty Crown OP 1", "Another OP"],
    ["Future Diary OP 1", "Mobile Suit Gundam Iron Blooded Orphans OP 2"],
    ["March Comes In Like A Lion OP 4", "Kore Wa Zombie Desu Ka OP 1"],
    ["Attack On Titan OP 1", "Carnival Phantasm OP 1"],
    ["Koi To Uso OP 1", "Gosick OP 1"],
    ["Little Witch Academia OP 1", "Gangsta OP 1"],
    ["Haikyuu OP 1", "Perfect Insider OP"],
    ["Taboo Tattoo OP 1", "Overlord S2 OP"],
    ["Slime OP 1", "Trigun"],
    ["Carole and Tuesday", "Keijo!!! OP 1"],
    ["Jojo part 5 OP 1", "Cardcaptor Sakura: Clear Card OP 1"],
    ["A Certain Magical Index III OP 2", "Amnesia OP 1"],
    ["Kyoukai no Kanata", "Naruto OP 4"],
    ["Deadman Wonderland OP 1", "Chivalry of a Failed Knight OP 1"],
    ["Jormungand OP 1", "Tsurune OP 1"],
    ["Kekkai Sensen OP 2", "Sailor Moon OP 1"],
    ["Guilty Crown OP 2", "Ghost In The Shell SAC OP 1"],
    ["Golden Kamuy OP 2", "Gatchaman Crowds OP 1"],
    ["Inu X Boku SS OP 1", "Absolute duo OP 1"],
    ["One Punch Man OP 1", "Danmachi OP 1"],
    ["K-ON! OP 1", "Akame Ga Kill OP 2"],
    ["Fate/Zero OP 2", "Umineko No Naku Koro Ni OP 3"],
    ["Madoka Magica op 1", "Gate OP 2"]
]

for (var i = 0; i < teams1.length; i++) {
  for (var j = 0; j < 2; j++) {
    teams1[i][j] = "<a href='" + vidlinks.get(teams1[i][j]) + "' target='_blank'>" + teams1[i][j] + "</a>"
    teams2[i][j] = "<a href='" + vidlinks.get(teams2[i][j]) + "' target='_blank'>" + teams2[i][j] + "</a>"
    teams3[i][j] = "<a href='" + vidlinks.get(teams3[i][j]) + "' target='_blank'>" + teams3[i][j] + "</a>"
  }
}

var tourneyData1 = {
    "teams":   teams1,
    "results": [            // List of brackets (single elimination, so only one bracket)
        [                     // List of rounds in bracket
            [                   // First round in this bracket
                // Set 1
                [14, 4 ],
                [15, 3 ],
                [12, 6 ],
                [ 8, 10],
                // Set 2
                [14, 13],
                [19, 8 ],
                [15, 12],
                [18, 9 ],
                // Set 3
                [15, 12],
                [13, 14],
                [15, 12],
                [16, 11],
                [10, 17],
                [24, 3 ],
                // Set 4
                [15, 8 ],
                [15, 8 ],
                [16, 7 ],
                [13, 10],
                [17, 6 ],
                [12, 11],
                // Set 5
                [ 9, 12],
                [12, 9 ],
                [18, 3 ],
                [ 7, 14],
                [12, 9 ],
                [ 8, 13],
                //Set 6
                [13,  5],
                [12,  6],
                [ 6, 12],
                [ 8, 10],
                [10,  8],
                [17,  1]
            ],
            [ // ROUND 2
                // Set 1
                [11,  9],
                [11,  9],
                [ 3, 17],
                [ 5, 15],
                [14,  6],
                [15,  5],
                [ 3, 17],
                [12,  8],
                // Set 2
                [12,  5],
                [ 4, 13],
                [ 8,  9],
                [10,  7],
                [ 8,  9],
                [ 8,  9],
                [10,  7],
                [ 4, 13]
            ],
            [ // ROUND 3
                // Set 1
                [13,  8],
                [10, 11],
                [ 5, 16],
                [17,  4],
                [12,  9],
                [ 6, 15],
                [13,  8],
                [ 3, 18]
            ]
        ]
    ]
}

var tourneyData2 = {
    "teams":   teams2,
    "results": [            // List of brackets (single elimination, so only one bracket)
        [                     // List of rounds in bracket
            [                   // First round in this bracket
                // Set 1
                [ 7,  4],
                [ 8,  3],
                [ 3,  8],
                [ 5,  6],
                [ 7,  4],
                [ 4,  7],
                // Set 2
                [ 8,  5],
                [13,  0],
                [10,  3],
                [ 7,  6],
                [10,  3],
                [10,  3],
                // Set 3
                [ 1, 10],
                [ 9,  2],
                [ 9,  2],
                [ 4,  7],
                [ 2,  9],
                [ 5,  6],
                // Set 4
                [ 7,  4],
                [ 7,  4],
                [ 6,  5],
                [ 6,  5],
                [ 6,  5],
                [ 7,  4],
                // Set 5
                [ 6,  3],
                [ 7,  2],
                [ 5,  4],
                [ 1,  8],
                [ 6,  3],
                [ 8,  1],
                [ 6,  3],
                [ 7,  2]
            ],
            [
                // Set 1
                [ 5, 10],
                [ 6,  9],
                [ 8,  7],
                [ 5, 10],
                [ 8,  7],
                [ 7,  8],
                [ 8,  7],
                [ 3, 12],
                // Set 2
                [ 8,  1],
                [ 1,  8],
                [ 4,  5],
                [ 2,  7],
                [ 1,  8],
                [ 1,  8],
                [ 5,  4],
                [ 4,  5]
            ],
            [
                // Set 1
                [ 7,  4],
                [ 1, 10],
                [ 4,  7],
                [ 5,  6],
                // Set 2
                [ 3,  6],
                [ 3,  6],
                [ 2,  7],
                [ 4,  5]
            ]
        ]
    ]
}

var tourneyData3 = {
    "teams":   teams3,
    "results": [            // List of brackets (single elimination, so only one bracket)
    ]
}

$(function() {
    $('#tourney-1').bracket({
      init: tourneyData1,
      teamWidth: Math.max(200, screen.width/6)
    })
  }
)

$(function() {
    $('#tourney-2').bracket({
      init: tourneyData2,
      teamWidth: Math.max(200, screen.width/6)
    })
  }
)

$(function() {
    $('#tourney-3').bracket({
      init: tourneyData3,
      teamWidth: Math.max(200, screen.width/6)
    })
  }
)
